name: '1Password'
description: 'Read items from a 1Password vault'
author: 'Brandon Evans'
inputs:
  device-id:
    require: false
    description: A base 32-encoded device ID. If this isn't provided as an input variable it must be provided as an OP_DEVICE environment variable.
  sign-in-address:
    required: true
    description: '1Password sign-in address'
  email-address:
    required: true
    description: '1Password username'
  secret-key:
    required: true
    description: '1Password secret key'
  master-password:
    required: true
    description: '1Password master password'
  items:
    required: true
    description: 'The vault and item names, and optionally new names, being requested.'
runs:
  using: 'node12'
  main: 'dist/index.js'
